### ISSUE TITLE
Update package.json for latest markdown-it version

### ISSUE THREAD

**Issue by gromain** [markdown-it/markdown-it-sub#1]
Hello,

I have troubles using this plugin in one of my scripts.
I use the `package.json` of my application to load this plugin through the dependencies list, however it seems like there is a problem with the version compatibility.
I load the latest markdown-it version (v8.3.1), but since the `package.json` of this plugin require `"^4.0.0"`, I think nodejs refuses to load it because it's not declared as compatible.
I believe the `package.json` could be updated to reflect the compatibility with the latest version.

Sincerely

**Comment by puzrin** [comment]
That's a development dependencies, those are not installed at production at all and are used for tests only. No changes needed.

**Comment by gromain** [comment]
Damn it! I'm sorry I didn't read properly! I guess 3AM work is not the most efficient ever...
